"""
WEBSCRAPING - É O PROCESSO DE COLETA DE DADOS AUTOMATIZADOS DA INTERNET
ALGUNS CASOS DE USO DO WEBSCRAPING:
-> MONITORAÇÃO DE PREÇOS
-> MONITORAÇÃO DE NOTICIAS
-> GERAÇAO DE LEADS (POTENCIAIS CLIENTES)
-> PESQUISA DE MERCADO
===> CONCEITOS IMPORTANTES DO WEBSCRAPING
-> CRAWLER: NEVEGA NA PAGINA WEB ALVO MAPEANDO TODAS AS PAGINAS, CAMINHOS, LINKS(INTERNOS E EXTERNOS),
    FORMULARIOS, RECURSOS PARA DOWNLOAD, ETC.
-> PARSING: ANALISE SINTATICA DA PAGINA WEB, TRANSFORMANDO O CODIGO HTML EM UMA REPRESENTAÇAO MAIS FACIL
    DE SER PROCESSADA.
-> SCRAPER: EXTRAI OS DADOS DA PAGINA ATRAVES DE SELETORES CSS, TAGS HTML, EXPRESSOES REGULARES, XPATH,
    OU UMA COMBINAÇAO DELES. NECESSITA CONHECIMENTO PREVIO DA ESTRUTURA DA PAGINA. EXISTEM METODOS PARA
    DIFICULTAR ESSE PROCESSO (OFUSCAÇAO)
-> OFUSCAÇAO: TECNICA UTILIZADA PARA EMBARALHAR OS DADOS DA PAGINA, DIFICULTANDO OU IMPOSSIBILITANDO O
    PROCESSO DE WEBSCRAPING.
"""